/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_system;

import com.sun.jdi.connect.spi.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author godfr
 */
public class pay extends javax.swing.JFrame {    
    java.sql.Connection conn = new dbConnect().dbcon();
    public pay() {
        initComponents();
        
        panel_result.setVisible(false);

        PreparedStatement pt = null;        
        Statement st;
        ResultSet rs;
        try {
            st = (Statement) conn.createStatement();
            String sql = "SELECT * FROM checkout";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                name.setText(rs.getString("name"));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        other_cost = new javax.swing.JTextField();
        medical_cost = new javax.swing.JTextField();
        treatment_cost = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_result = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        total_price = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ค่ายา");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        jPanel1.setBackground(new java.awt.Color(26, 1, 91));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" ชื่อผู้ป่วย");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ค่ารักษาพยาบาล / ยา");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        name.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("?");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ค่ายา");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        other_cost.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        other_cost.setText("0");
        other_cost.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 1));
        jPanel1.add(other_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 140, -1));

        medical_cost.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        medical_cost.setText("0");
        medical_cost.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 1));
        jPanel1.add(medical_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 140, -1));

        treatment_cost.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        treatment_cost.setText("0");
        treatment_cost.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 1));
        jPanel1.add(treatment_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 140, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ยินยัน");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 100, 40));

        jLabel6.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ค่ารักษาพยาบาล");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" อื่นๆ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        panel_result.setBackground(new java.awt.Color(26, 1, 91));
        panel_result.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Sarabun", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ยอดเงินทั้งหมด");
        panel_result.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        total_price.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        total_price.setForeground(new java.awt.Color(255, 255, 255));
        total_price.setText("?");
        panel_result.add(total_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Sarabun", 0, 14)); // NOI18N
        jButton2.setText("แสดงใบเสร็จ");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        panel_result.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 69, -1, -1));

        jPanel1.add(panel_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        total_price.setText((Integer.parseInt(treatment_cost.getText()) + Integer.parseInt(medical_cost.getText()) + Integer.parseInt(other_cost.getText())) + " บาท");
        panel_result.setVisible(true);
        
        PreparedStatement pt = null;
        try {
            String sql = "UPDATE checkout SET treatment_cost="+treatment_cost.getText()+", medical_cost="+medical_cost.getText()+", other_cost="+other_cost.getText()+" WHERE 1=1 ";
            pt = conn.prepareStatement(sql);
            pt.execute();
        } catch (SQLException ex) {
            System.out.println("error");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        dispose();
        new bill().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField medical_cost;
    private javax.swing.JLabel name;
    private javax.swing.JTextField other_cost;
    private javax.swing.JPanel panel_result;
    private javax.swing.JLabel total_price;
    private javax.swing.JTextField treatment_cost;
    // End of variables declaration//GEN-END:variables
}
